In [62]:
############## Assessment Number 2, Maj Lakhan Singh, Subject: Data Science, Branch : M.tech, Regt:24-27-02 ############

In [20]:
# Question No1 : Solution :-

#a) Create a variable named var1 that stores an array of numbers from 0 to 30,
#inclusive. Print var1 and its shape. Hint : arange

#My understanding is that since 31 elements are there, it cannot be converted to 2d matrix of dim such as 5X6,6X5, 10X3 etc.
#Therefore , i am making a 2d matrix  of 31X1 dim.

import numpy as np

var1 = np.arange(31)
print(var1,var1.shape,var1.ndim)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30] (31,) 1


In [24]:
#b) Change var2 to a validly-shaped two-dimensional matrix and store it in a
#new variable called var2. Print var2 and its shape. Hint: Use the reshape function

var2=var1.reshape((31,1))
print(var2,var2.shape,var1.ndim)


[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]] (31, 1) 1


In [26]:

#c) Create a third variable, var3 that reshapes it into a valid three-dimensional shape.
#Print var3 and its shape.


var3=var2.reshape(31,1,1)
print(var3,var3.shape,var3.ndim)

[[[ 0]]

 [[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]

 [[12]]

 [[13]]

 [[14]]

 [[15]]

 [[16]]

 [[17]]

 [[18]]

 [[19]]

 [[20]]

 [[21]]

 [[22]]

 [[23]]

 [[24]]

 [[25]]

 [[26]]

 [[27]]

 [[28]]

 [[29]]

 [[30]]] (31, 1, 1) 3


In [28]:
"""
d) Use two-dimensional array indexing to set the first value in the second row of var2
to -1. Now look at var1 and var3. Did they change? Explain what’s
going on. (Hint: does reshape return a view or a copy?)
"""

var2[1][0]=-1
print(var2)
print(var1,var3)  

#  Comment:- reshape returns the view on original data and therefore the changes are reflected in var1 and var3. It does not make copy of data.

[[ 0]
 [-1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]
[ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30] [[[ 0]]

 [[-1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]

 [[12]]

 [[13]]

 [[14]]

 [[15]]

 [[16]]

 [[17]]

 [[18]]

 [[19]]

 [[20]]

 [[21]]

 [[22]]

 [[23]]

 [[24]]

 [[25]]

 [[26]]

 [[27]]

 [[28]]

 [[29]]

 [[30]]]


In [30]:
"""
e) Another thing that comes up a lot with array shapes is thinking about how to
aggregate over specific dimensions. Figure out how the NumPy sum function
works (and the axis argument in particular) and do the following:
(i) Sum var3 over its second dimension and print the result.
(ii) Sum var3 over its third dimension and print the result.
(iii) Sum var3 over both its first and third dimensions and print the result.
"""

sum_2dim = np.sum(var3, axis=1)
print("Sum over second dimension:\n", sum_2dim )

sum_3dim = np.sum(var3, axis=2)
print("Sum over third dimension:\n", sum_3dim )


sum_first_third_dim = np.sum(var3, axis=(0, 2))
print("Sum over first and third dimensions:\n", sum_first_third_dim)


Sum over second dimension:
 [[ 0]
 [-1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]
Sum over third dimension:
 [[ 0]
 [-1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]
Sum over first and third dimensions:
 [463]


In [36]:

#f) Write code to do the following:
#(i) Slice out the second row of var2 and print it.
#(ii) Slice out the last column of var2 using the -1 notation and print it.
#(iii) Slice out the top right 2 × 2 submatrix of var2 and print it.

#(i)
second_row = var2[1, :]
print("Second row of var2:", second_row)

#(ii)
last_col = var2[:, -1]
print("Last column of var2:", last_col)
#(iii)
#2x2 submatrix does not exist in above case due to uncompatiablity of matrix dimension

Second row of var2: [-1]
Last column of var2: [ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]


In [38]:
#Question 2 
solution:-
"""
a) The most basic kind of broadcast is with a scalar, in which you can perform a
binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to
perform that operation with the scalar for every element of the array. To try this
out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.
"""

import numpy as np

arr = np.arange(10) + 1
print("Vector:", arr)


Vector: [ 1  2  3  4  5  6  7  8  9 10]


In [54]:

#b) Now, create a 10 × 10 matrix A in which Ai j = i + j. You’ll be able to do this
#using the vector you just created, and adding it to a reshaped version of itself.

i=arr
j= arr.reshape(10, 1)
Matrix_A = i + j
print("Matrix A:\n", Matrix_A)


Matrix A:
 [[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


In [46]:
"""
c) A very common use of broadcasting is to standardize data, i.e., to make it have
zero mean and unit variance. First, create a fake “data set” with 50 examples,
each with five dimensions.
import numpy.random as npr
data = np.exp(npr.randn ( 50 , 5 ) )
"""

import numpy.random as npr

data = np.exp(npr.randn(50, 5))


In [ ]:
d) You don’t worry too much about what this code is doing at this stage of the
course, but for completeness: it imports the NumPy random number generation
library, then generates a 50 × 5 matrix of standard normal
random variates and exponentiates them. The effect of this is to have a pretend
data set of 50 independent and identically-distributed vectors from a log-normal
distribution.


In [56]:
"""
e) Now, compute the mean and standard deviation of each column. This should
result in two vectors of length 5. You’ll need to think a little bit about how to use
the axis argument to mean and std. Store these vectors into variables and print
both of them.
"""

mean = np.mean(data, axis=0)
std_deviation = np.std(data, axis=0)
print("Mean:", mean)
print("Standard Deviation:", std_deviation)


Mean: [1.26160789 1.89322192 2.16547644 1.77339355 1.51705035]
Standard Deviation: [1.38780578 1.64664026 3.35834807 2.99160369 1.63740978]


In [60]:
"""
f) Now standardize the data matrix by 1) subtracting the mean off of each column,
and 2) dividing each column by its standard deviation. Do this via broadcasting,
and store the result in a matrix called normalized. To verify that you successfully
did it, compute the mean and standard deviation of
the columns of normalized and print them out.
"""
normalized_data = (data - mean) / std_dev
print(" Normalized Data:\n ", normalized_data)

# Verify the mean and standard deviation of the columns of normalized data
normalized_mean = np.mean(normalized_data, axis=0)
normalized_std_dev = np.std(normalized_data, axis=0)
print("Normalized Mean:", normalized_mean)
print("Normalized Standard Deviation:", normalized_std_dev)


Normalized Data:
 [[ 4.87041525e-01 -9.88076421e-01 -3.49204789e-01 -4.30336321e-01
  -4.44617297e-01]
 [ 3.13421576e+00 -5.55664539e-01 -1.11939396e-01  1.31985035e+00
  -7.88977587e-01]
 [-2.85628026e-01 -7.94839912e-02 -1.74550270e-01 -3.69805487e-02
  -5.46131027e-03]
 [-1.25117200e-01 -8.52550042e-01 -3.45120099e-01 -4.20316232e-01
  -5.99298768e-01]
 [ 6.38951203e-01  4.12517960e-01  9.06393026e-01 -4.34468960e-01
  -7.26837579e-01]
 [ 7.47655071e-01 -5.19313549e-01 -3.70977165e-01 -2.71098749e-01
  -1.20312024e-01]
 [-3.83678346e-01  1.28074554e+00  3.30728671e-01 -8.80048310e-02
   3.66944689e-01]
 [-5.34381705e-01  3.24206733e+00 -5.65007778e-01 -3.30131709e-01
  -2.85717101e-01]
 [-7.14942045e-01  6.38285665e-01  1.46258901e+00 -2.22989654e-01
  -5.44161228e-01]
 [ 5.53869643e-01  7.61611455e-01 -5.75666033e-01 -5.27725784e-01
  -7.11338969e-01]
 [-5.49953911e-01 -6.11339377e-01 -1.89253450e-01  4.89891598e-02
  -2.14465349e-01]
 [-5.50020630e-01 -9.18749022e-01  1.59370049e-

In [ ]:
#################------------------------------------------------------------------#######################################

In [70]:
"""
Question 3. Solution:-
a) A Vandermonde matrix is a matrix generated from a vector in which each column
of the matrix is an integer power starting from zero. So, if I have a column vector
[x1, x2, . . . , xN]
T
, then the associated (square) Vandermonde matrix would be
Use what you learned about broadcasting in the previous problem to write a
function that will produce a Vandermonde matrix for a vector [1, 2, . . . ,N]T
forany N. Do it without using a loop. Here’s a stub to get you started:
def vandermonde (N):
vec = np.arange (N) +1
Use your function for N = 12, store it in variable named vander, and print the
result.
# write your code here .
"""

import numpy as np
import numpy.linalg as la

def vandermonde(N):
    vec = np.arange(N) + 1
    vander = vec ** np.arange(N).reshape(N, 1)
    return vander

vander = vandermonde(12)  # N=12 as per question 
print("Vandermonde Matrix for a Vector:\n", vander)




Vandermonde Matrix for a Vector:
 [[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           3           4           5           6
            7           8           9          10          11          12]
 [          1           4           9          16          25          36
           49          64          81         100         121         144]
 [          1           8          27          64         125         216
          343         512         729        1000        1331        1728]
 [          1          16          81         256         625        1296
         2401        4096        6561       10000       14641       20736]
 [          1          32         243        1024        3125        7776
        16807       32768       59049      100000      161051      248832]
 [          1          64         729        4096       15625       4665

In [68]:
"""
b) Now, let’s make a pretend linear system problem with this matrix. Create a vector
of all ones, of length 12 and call it x. Perform a matrix-vector multiplication of
vander with the vector you just created and store that in a new vector and call it b.
Print the vector b.
"""

x = np.ones(12)
b = np.dot(vander, x)
print("Vector b:\n", b)





Vector b:
 [1.20000000e+01 7.80000000e+01 6.50000000e+02 6.08400000e+03
 6.07100000e+04 6.30708000e+05 6.73595000e+06 7.33994040e+07
 8.12071910e+08 5.02098436e+08 3.98488294e+09 6.74822371e+09]


In [74]:
"""
c) First, solve the linear system the naïve way, pretending like you don’t know x.
Import numpy.linalg, invert V and multiply it by b. Print out your result. What
should you get for your answer? If the answer is different than what you
expected, write a sentence about that difference.
"""

vander_inv = la.inv(vander)
x_naive = np.dot(vander_inv, b)
print("Naive way Solution to above linear equation x:\n", x_naive)


Naive way Solution to above linear equation x:
 [0.99996236 1.00004554 0.99998787 1.00000833 0.99999357 1.00000279
 0.99999964 0.99999991 0.99999995 1.00000004 1.         1.        ]


In [76]:
"""
d) Now, solve the same linear system using solve. Print out the result. Does it seem
more or less in line with what you’d expect?

"""
x_solve = la.solve(vander, b)
print("Solution using solve x:\n", x_solve)

"""
Reason:-Since we know that  X is a vector of all ones, the expected result should be a vector of 1's. However the result is different,
it might be due to numerical instability or precision issues inherent in inverting a Vandermonde matrix which is due to the
floating point representation in Python language.
"""

Solution using solve x:
 [0.99999981 1.00000104 0.99999744 1.00000355 0.99999713 1.00000123
 0.99999984 0.99999996 0.99999998 1.00000002 1.         1.        ]


"\nReason:-Since we know that  X is a vector of all ones, the expected result should be a vector of 1's. However the result is different,\nit might be due to numerical instability or precision issues inherent in inverting a Vandermonde matrix which is due to the\nfloating point representation in Python language.\n"

In [ ]:
###      https://github.com/Lakhansingh2024/lakhansingh_24-27-02.git